### ISSUE TITLE
__PrinceGeorgesCountySummary

### ISSUE THREAD

**Issue by jseipp** [kerrymcmahon/Prince-Georges-County-Stormwater#3]
The following is a summary of sites:

| **PG-GRP1-JMT** |  |  |  |
| --- | --- | --- | --- |
| **SITE NAME** | **SITE STATUS** | **CONFLICT** | **SOURCE** |
| PGGr1-JMT-001 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-002 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-003 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-004 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-005 | REMOVE |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-006 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-007 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-008 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-009 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-010 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-012 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-013 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-014 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-015 | REMOVE |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-016 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-017 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-018 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-019 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-020 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-023 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-024 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-025 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-027 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-028 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-029 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-030 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-031 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-032 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-033 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-034 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-036 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-037 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-038 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-039 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-040 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-041 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-045 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-046 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-047 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-048 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-049 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-050 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-051 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-052 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-053 | REMOVE |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-054 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-055 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-057 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-058 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-059 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-060 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-061 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-062 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-063 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-064 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-065 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-066 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-067 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-068 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-069 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-070 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-074 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-075 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-076 | REMOVE |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-077 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-078 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-079 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-080 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-081 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-082 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-083 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-084 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-085 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-086 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-087 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-088 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-090 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-091 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-092 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-093 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-094 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-095 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-096 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-097 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-098 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-099 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-100 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-101 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-102 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-103 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-104 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-105 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-106 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-107 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-108 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-110 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-111 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-112 | REMOVE |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-113 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-114 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-115 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-117 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-119 | OK |  | PG-GRP1-JMT-FI |
| PGGr1-JMT-120 | OK |  | PG-GRP1-JMT-FI |
|  |  |  |  |
|  |  |  |  |

| **PG-GRP2-JMT** |  |  |  |
| --- | --- | --- | --- |
| **SITE NAME** | **SITE STATUS** | **CONFLICTS** | **SOURCE** |
| PGGr2-JMT-001 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-002 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-003 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-004 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-005 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-006 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-007 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-008 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-009 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-010 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-011 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-012 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-013 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-014 | ON HOLD | CONFLICT_00045 | PG-GRP2-JMT-FI |
| PGGr2-JMT-015 | REMOVE |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-016 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-017 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-018 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-019 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-020 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-021 | REMOVE |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-022 | REMOVE |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-023 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-024 | REMOVE |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-025 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-026 | REMOVE |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-027 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-028 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-029 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-030 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-031 | REMOVE |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-032 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-033 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-034 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-035 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-036 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-037 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-038 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-039 | REMOVE |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-040 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-041 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-042 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-043 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-044 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-045 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-046 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-047 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-048 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-049 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-050 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-051 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-052 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-053 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-054 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-055 | REMOVE |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-056 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-057 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-058 | REMOVE |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-059 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-060 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-064 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-065 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-066 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-067 | On Hold | CONFLICT_00018 | PG-GRP2-JMT-FI |
| PGGr2-JMT-068 | On Hold | CONFLICT_00018 | PG-GRP2-JMT-FI |
| PGGr2-JMT-069 | On Hold | CONFLICT_00018 | PG-GRP2-JMT-FI |
| PGGr2-JMT-070 | On Hold | CONFLICT_00018 | PG-GRP2-JMT-FI |
| PGGr2-JMT-071 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-072 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-073 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-074 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-075 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-076 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-077 | On Hold | CONFLICT_00018 | PG-GRP2-JMT-FI |
| PGGr2-JMT-078 | On Hold | CONFLICT_00018 | PG-GRP2-JMT-FI |
| PGGr2-JMT-079 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-080 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-081 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-082 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-083 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-084 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-085 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-086 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-087 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-088 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-089 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-090 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-091 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-092 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-093 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-094 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-095 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-096 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-097 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-098 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-099 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-100 | FYI | CONFLICT_00019 | PG-GRP2-JMT-FI |
| PGGr2-JMT-101 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-102 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-103 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-104 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-105 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-106 | OK |  | PG-GRP2-JMT-FI |
| PGGr2-JMT-107 | REMOVE |  | PG-GRP2-JMT-FI |

**Comment by mparlakian** [comment]
A couple PGGr2 sites show conflict with TMDL tree sites on their hard copy maps, but the data layers I have do not appear to show a conflict (sites 013, 006).  Do we generally ask the consultant to update their hard copy map?  Do we provide an updated TMDL tree layer?
![map example](https://cloud.githubusercontent.com/assets/13119851/9137765/f65c4678-3ced-11e5-9463-aa8a438ad24c.jpg)

**Comment by kerrymcmahon** [comment]
This at one time was a potential tree site, however the tree team remved it from consideration to make room for stormwater. We have updated our process so that the teams DO NOT need to worry about TREE_SITE_SELECTION (we will deal with that through the conflict process). They only need to focus on the TMDL tree assets (LUCHANGE_BMP). There are no assets here. They should not have any reason to update maps - since this is correctly labeled as "potential."
